### ISSUE TITLE
scv.pl.velocity_embedding_stream() - AttributeError: can't set attribute

### ISSUE THREAD

**Issue by colin893** [theislab/cellrank#1073]
Created a conda environment with cellrank and all required modules, followed the tutorial to be sure everything was fine but got an error at the very last command : AttributeError: can't set attribute

```python
mport sys
import scvelo as scv
import scanpy as sc
import cellrank as cr
import numpy as np

scv.settings.verbosity = 3
scv.settings.set_figure_params("scvelo")
cr.settings.verbosity = 2

import warnings

warnings.simplefilter("ignore", category=UserWarning)
warnings.simplefilter("ignore", category=FutureWarning)
warnings.simplefilter("ignore", category=DeprecationWarning)

adata = cr.datasets.pancreas()
scv.pl.proportions(adata)
adata

scv.pp.filter_and_normalize(adata, min_shared_counts=20, n_top_genes=2000)
sc.tl.pca(adata)
sc.pp.neighbors(adata, n_pcs=30, n_neighbors=30)
scv.pp.moments(adata, n_pcs=None, n_neighbors=None)

scv.tl.recover_dynamics(adata, n_jobs=8)

scv.tl.velocity(adata, mode="dynamical")
scv.tl.velocity_graph(adata)

scv.tl.velocity(adata, mode="dynamical")
scv.tl.velocity_graph(adata)

scv.pl.velocity_embedding_stream(
adata, basis="umap", legend_fontsize=12, title="", smooth=0.8, min_mass=4
)

```

```pytb
scv.pl.velocity_embedding_stream(
... adata, basis="umap", legend_fontsize=12, title="", smooth=0.8, min_mass=4 
... )
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/velocity_embedding_stream.py", line 252, in velocity_embedding_stream
    ax = scatter(
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/scatter.py", line 668, in scatter
    set_legend(
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/scvelo/plotting/utils.py", line 555, in set_legend
    obs_vals.cat.categories = obs_vals.cat.categories.astype(str)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/base.py", line 178, in __setattr__
    object.__setattr__(self, key, value)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/accessor.py", line 99, in _setter
    return self._delegate_property_set(name, new_values)
  File "/home/u/s154838/miniconda3/envs/cellrank4/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 2460, in _delegate_property_set
    return setattr(self._parent, name, new_values)
AttributeError: can't set attribute
```

#### Versions:

#> >>> cellrank.logging.print_versions()
cellrank==1.5.1 scanpy==1.9.3 anndata==0.9.1 numpy==1.21.6 numba==0.57.0 scipy==1.11.0 pandas==2.0.2 pygpcca==1.0.4 scikit-learn==1.2.2 statsmodels==0.14.0 scvelo==0.2.5 pygam==0.8.0 matplotlib==3.7.1 seaborn==0.12.2

**Comment by Marius1311** [comment]
Hi @colin893, is this really a CellRank error? Looks like you only called scVelo functions. Please consider moving this issue to the scVelo repo, where it might fit better.
