### ISSUE TITLE
Compatibility problems with python >=3.10

### ISSUE THREAD

**Issue by PaMartini** [theislab/cellrank#1153]
I have Python 3.10 and cellrank 1.5.1 installed in my environment.

Traceback (most recent call last):
  File ".../src/pseudotime_analysis.py", line 7, in <module>
    from cellrank.kernels import CytoTRACEKernel
  File ".../lib/python3.10/site-packages/cellrank/__init__.py", line 2, in <module>
    import cellrank.pl
  File ".../lib/python3.10/site-packages/cellrank/pl/__init__.py", line 1, in <module>
    from cellrank.pl._graph import graph
  File ".../lib/python3.10/site-packages/cellrank/pl/_graph.py", line 11, in <module>
    from cellrank.ul._docs import d
  File ".../lib/python3.10/site-packages/cellrank/ul/__init__.py", line 1, in <module>
    import cellrank.ul.models
  File ".../lib/python3.10/site-packages/cellrank/ul/models/__init__.py", line 1, in <module>
    from cellrank.ul.models._base_model import BaseModel, FailedModel, FittedModel
  File ".../lib/python3.10/site-packages/cellrank/ul/models/_base_model.py", line 14, in <module>
    from cellrank.tl._enum import ModeEnum
  File ".../lib/python3.10/site-packages/cellrank/tl/__init__.py", line 2, in <module>
    import cellrank.tl.estimators
  File ".../lib/python3.10/site-packages/cellrank/tl/estimators/__init__.py", line 2, in <module>
    from cellrank.tl.estimators.terminal_states import GPCCA, CFLARE, TermStatesEstimator
  File ".../lib/python3.10/site-packages/cellrank/tl/estimators/terminal_states/__init__.py", line 1, in <module>
    from cellrank.tl.estimators.terminal_states._gpcca import GPCCA
  File ".../lib/python3.10/site-packages/cellrank/tl/estimators/terminal_states/_gpcca.py", line 22, in <module>
    from cellrank.tl.estimators._utils import SafeGetter
  File ".../lib/python3.10/site-packages/cellrank/tl/estimators/_utils.py", line 4, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (.../lib/python3.10/collections/__init__.py)

**Comment by Marius1311** [comment]
Hi @PaMartini, please upgrade to CellRank 2.

**Comment by michalk8** [comment]
Unfortunately, 1.5.1 is fairly old at this point, please install cellrank>=2.0; closing this.
