### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#123]
@VolkerBergen encountered:

```
~/theislab/packages/cellrank/cellrank/tools/estimators/_gppca.py in <module>
      3 from types import MappingProxyType
      4 from anndata import AnnData
----> 5 from msmtools.analysis.dense.gpcca import GPCCA as _GPPCA
      6 from scanpy import logging as logg
      7 from scipy.stats import entropy

ModuleNotFoundError: No module named 'msmtools.analysis.dense.gpcca'
```

**Comment by Marius1311** [comment]
@VolkerBergen , can you try removing and re-installing cellrank? The dependencies have changed with the last PR.

**Comment by VolkerBergen** [comment]
Currently not installable
<details>
<summary> Error </summary>
```pytb
  ERROR: Command errored out with exit status 1:
   command: /Users/volker.bergen/anaconda3/envs/py37/bin/python /Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/63/zhs0n9ps13gb512434w1c8kcrgy342/T/pip-build-env-aeglydkj/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel
       cwd: None
  Complete output (44 lines):
  Traceback (most recent call last):
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/__main__.py", line 26, in <module>
      sys.exit(_main())
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/commands/__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 24, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/cli/req_command.py", line 16, in <module>
      from pip._internal.index.package_finder import PackageFinder
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/index/package_finder.py", line 21, in <module>
      from pip._internal.index.collector import parse_links
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_internal/index/collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_vendor/requests/__init__.py", line 114, in <module>
      from . import utils
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
      from . import certs
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_vendor/requests/certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_vendor/certifi/__init__.py", line 1, in <module>
      from .core import contents, where
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip/_vendor/certifi/core.py", line 12, in <module>
      from importlib.resources import read_text
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/importlib/resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "/Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/volker.bergen/anaconda3/envs/py37/bin/python /Users/volker.bergen/anaconda3/envs/py37/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/63/zhs0n9ps13gb512434w1c8kcrgy342/T/pip-build-env-aeglydkj/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools setuptools_scm wheel Check the logs for full command output.
```
</details>

**Comment by michalk8** [comment]
Something's wrong with the `typing` module. What's your python version?

**Comment by michalk8** [comment]
Maybe relevant (Python 3.7): https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry

**Comment by VolkerBergen** [comment]
good to know! thx, installed and env fixed.

**Comment by VolkerBergen** [comment]
Yet, the first-mentioned error hinders importing cellrank.

**Comment by Marius1311** [comment]
any idea what was going on there @VolkerBergen ?

**Comment by VolkerBergen** [comment]
Can't reproduce unfortunately, maybe it was specific to my env. Run again in clean py3.6|3.7|3.8 envs, which all worked perfectly.

**Comment by Marius1311** [comment]
okay cool, thanks for checking! I'm closing this now.
