### ISSUE TITLE
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'

### ISSUE THREAD

**Issue by wzyfudan** [theislab/cellrank#1232]
conda create -n cellrank python=3.11
conda activate cellrank
conda install -c conda-forge cellrank

I meet a problem when i enter python type import cellrank
>>> import cellrank as cr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/__init__.py", line 2, in <module>
    import cellrank.pl
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/pl/__init__.py", line 1, in <module>
    from cellrank.pl._graph import graph
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/pl/_graph.py", line 11, in <module>
    from cellrank.ul._docs import d
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/ul/__init__.py", line 1, in <module>
    import cellrank.ul.models
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/ul/models/__init__.py", line 1, in <module>
    from cellrank.ul.models._base_model import BaseModel, FailedModel, FittedModel
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/ul/models/_base_model.py", line 14, in <module>
    from cellrank.tl._enum import ModeEnum
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/tl/__init__.py", line 1, in <module>
    import cellrank.tl.kernels
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/tl/kernels/__init__.py", line 1, in <module>
    from cellrank.tl.kernels._base_kernel import Kernel
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/cellrank/tl/kernels/_base_kernel.py", line 21, in <module>
    import scvelo as scv
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/__init__.py", line 5, in <module>
    from scvelo import datasets, logging
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/datasets/__init__.py", line 1, in <module>
    from ._datasets import (
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/datasets/_datasets.py", line 10, in <module>
    from scvelo.core import cleanup
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/core/__init__.py", line 1, in <module>
    from ._anndata import (
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/core/_anndata.py", line 15, in <module>
    from scvelo import logging as logg
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/logging.py", line 12, in <module>
    from scvelo import settings
  File "/home/wangz/miniconda3/envs/cellrank/lib/python3.11/site-packages/scvelo/settings.py", line 91, in <module>
    warnings.filterwarnings("ignore", category=cbook.mplDeprecation)
                                               ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'matplotlib.cbook' has no attribute 'mplDeprecation'

**Comment by wzyfudan** [comment]
Package           Version
----------------- -----------
anndata           0.10.9
array_api_compat  1.9.1
asttokens         2.0.5
cached-property   1.5.2
cellrank          1.5.1
certifi           2024.8.30
click             8.1.7
colorama          0.4.6
comm              0.2.1
contourpy         1.3.0
cycler            0.12.1
debugpy           1.6.7
decorator         5.1.1
docrep            0.3.2
exceptiongroup    1.2.2
executing         0.8.3
fonttools         4.54.1
future            1.0.0
get-annotations   0.1.2
h5py              3.12.1
ipykernel         6.29.5
ipython           8.27.0
jedi              0.19.1
joblib            1.4.2
jupyter_client    8.6.0
jupyter_core      5.7.2
kiwisolver        1.4.7
legacy-api-wrap   1.4
llvmlite          0.43.0
loompy            3.0.6
matplotlib        3.9.2
matplotlib-inline 0.1.6
mpi4py            4.0.1
munkres           1.1.4
natsort           8.4.0
nest-asyncio      1.6.0
networkx          3.4.2
numba             0.60.0
numpy             2.0.2
numpy-groupies    0.11.2
packaging         24.1
pandas            2.2.3
parso             0.8.3
patsy             0.5.6
petsc4py          3.22.0
pexpect           4.8.0
pillow            11.0.0
pip               24.2
platformdirs      3.10.0
progressbar2      4.5.0
prompt-toolkit    3.0.43
psutil            5.9.0
ptyprocess        0.7.0
pure-eval         0.2.2
pygam             0.9.1
Pygments          2.15.1
pygpcca           1.0.4
pynndescent       0.5.13
pyparsing         3.2.0
python-dateutil   2.9.0.post0
python-utils      3.8.2
pytz              2024.1
pyzmq             25.1.2
scanpy            1.10.3
scikit-learn      1.5.2
scipy             1.14.1
scvelo            0.2.5
seaborn           0.13.2
session-info      1.0.0
setuptools        75.1.0
six               1.16.0
slepc4py          3.22.0
stack-data        0.2.0
statsmodels       0.14.4
stdlib-list       0.11.0
threadpoolctl     3.5.0
tornado           6.4.1
tqdm              4.66.6
traitlets         5.14.3
typing_extensions 4.11.0
tzdata            2024.2
umap-learn        0.5.7
unicodedata2      15.1.0
wcwidth           0.2.5
wheel             0.44.0
wrapt             1.16.0

**Comment by WeilerP** [comment]
@wzyfudan, I cannot reproduce the error. I just installed CellRank in a new environment like you did on different systems, and everything works as expected. The underlying issue is with scVelo, but the issue was resolved some time ago.

**Comment by wzyfudan** [comment]
Thank you for your help. I already install cellrank in my Local computer without issue. Maybe there are some bugs in my servers.
