### ISSUE TITLE
Memory error for very large matrix

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#210]
Upon running
```
from cellrank.tools.kernels import PalantirKernel
pk = PalantirKernel(adata, time_key='dpt_pseudotime').compute_transition_matrix()
print(pk)
from cellrank.tools import GPCCA
g = GPCCA(pk)
print(g)
g.compute_schur(n_components=20)
g.plot_spectrum()
```
the following exception is raised:
```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-40-0afe6e8f9211> in <module>
----> 1 g.compute_schur(n_components=20,method="krylov")
      2 g.plot_spectrum()

~/miniconda3/envs/gpcca/lib/python3.7/site-packages/cellrank/tools/estimators/_gppca.py in compute_schur(self, n_components, initial_distribution, method, which, alpha)
    294         self._gpcca = _GPPCA(self._T, eta=initial_distribution, z=which, method=method)
    295         try:
--> 296             self._gpcca._do_schur_helper(n_components)
    297         except ValueError:
    298             logg.warning(

~/miniconda3/envs/gpcca/lib/python3.7/site-packages/msmtools/analysis/dense/gpcca.py in _do_schur_helper(self, m)
   1081                         print('INFO: Using pre-computed schur decomposition')
   1082         else:
-> 1083             self.X, self.R, self.eigenvalues = _do_schur(self.P.copy(), self.eta, m, self.z, self.method)
   1084 
   1085     def minChi(self, m_min, m_max):

~/miniconda3/envs/gpcca/lib/python3.7/site-packages/msmtools/analysis/dense/gpcca.py in _do_schur(P, eta, m, z, method, tol_krylov)
    246         # Transform the orthonormalized Schur vectors of P_bar back
    247         # to orthonormalized Schur vectors X of P.
--> 248         X = np.diag(1. / np.sqrt(eta)).dot(Q)
    249         # Set first (Schur) vector equal 1.
    250         X[:, 0] = 1.0

<__array_function__ internals> in diag(*args, **kwargs)

~/miniconda3/envs/gpcca/lib/python3.7/site-packages/numpy/lib/twodim_base.py in diag(v, k)
    273     if len(s) == 1:
    274         n = s[0]+abs(k)
--> 275         res = zeros((n, n), v.dtype)
    276         if k >= 0:
    277             i = k

MemoryError: Unable to allocate 320. GiB for an array with shape (207394, 207394) and data type float64
```

**Comment by Marius1311** [comment]
The problem is here: ` X = np.diag(1. / np.sqrt(eta)).dot(Q)`. Q will be a dense matrix of shape `n_samples x n_components`. So it's large, but not problematic. The problem probably is `np.diag(1. / np.sqrt(eta))`, because that creates a dense matrix of shape `n_samples x n_samples` . 

We should be able to fix this.

**Comment by Marius1311** [comment]
@giovp, that's the memory error you experienced. Did my recent PR fix that for you?

**Comment by giovp** [comment]
installs but does not import
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-76a7a5a493ce> in <module>
     10 from scipy import sparse
     11 
---> 12 import cellrank as cr
     13 import scvelo as scv
     14 

~/cellrank/cellrank/__init__.py in <module>
      2 from scanpy import settings
      3 
----> 4 import cellrank.tools as tl
      5 import cellrank.utils as ul
      6 import cellrank.datasets

~/cellrank/cellrank/tools/__init__.py in <module>
      3 from cellrank.tools._utils import partition, cyto_trace
      4 from cellrank.tools._lineage import Lineage
----> 5 from cellrank.tools._lineages import lineages
      6 from cellrank.tools.estimators import GPCCA, CFLARE
      7 from cellrank.tools._root_final import root_states, final_states

~/cellrank/cellrank/tools/_lineages.py in <module>
     11 from cellrank.tools.kernels import VelocityKernel
     12 from cellrank.tools._constants import LinKey, StateKey, Direction, _transition
---> 13 from cellrank.tools.estimators import GPCCA, CFLARE
     14 from cellrank.tools.estimators._base_estimator import BaseEstimator
     15 

~/cellrank/cellrank/tools/estimators/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from cellrank.tools.estimators._gppca import GPCCA
      3 from cellrank.tools.estimators._cflare import CFLARE

~/cellrank/cellrank/tools/estimators/_gppca.py in <module>
     35 from cellrank.tools.kernels._kernel import KernelExpression
     36 from cellrank.tools.estimators._base_estimator import BaseEstimator
---> 37 from cellrank._vendor.msmtools.analysis.dense.gpcca import GPCCA as _GPPCA
     38 
     39 # whether to remove overlapping cells from both states, or assign them to the most likely clusters

ModuleNotFoundError: No module named 'cellrank._vendor'
```

also, running `vendorize` as per installation instruction returned `-bash: vendorize: command not found`

Will have a look how to fix it.

Everything done on the server centos8 with conda envs

**Comment by Marius1311** [comment]
did you run `python-vendorize`?

**Comment by Marius1311** [comment]
We went through quite a few updates to our installation instructions recently, maybe have a quick look: https://cellrank.readthedocs.io/en/latest/installation.html

**Comment by giovp** [comment]
when I was installing it, it was written `vendorize` not `python-vendorize`.
Now tried it but still error
```
(gpcca) [giovanni.palla@icb-lisa cellrank]$ python-vendorize --user
-bash: /home/icb/giovanni.palla/miniconda3/envs/gpcca/bin/python-vendorize: Permission denied
```

**Comment by Marius1311** [comment]
@michalk8 , what can we do about this?

**Comment by Marius1311** [comment]
In the meantime, @giovp , just install via pip, `pip install cellrank`, that should also include my recent changes to the msmtools for.

**Comment by michalk8** [comment]
@giovp `python-vendorize` doesn't have `--user` option, it's 1 argument, if any, should be a path to `vendorize.toml` (not needed if running from CellRank's root directory), so I'd try it without it.
If that doesn't fix it, I'd check 2 things:
- the permissions as `ls -la /home/michal/.miniconda3/envs/cellrank/bin/python-vendorize` (should have `x` for user, e.g. `-rwxr-xr-x`)
- which python is being used as `head -n 1 /home/icb/giovanni.palla/miniconda3/envs/gpcca/bin/python-vendorize` (in my `cellrank` environment, it's `#!/home/michal/.miniconda3/envs/cellrank/bin/python`)

**Comment by Marius1311** [comment]
thanks Mike!

**Comment by giovp** [comment]
python-vendorize still does not work from root cell rank directory. I had to change chmod 700 the file in the conda env to be able to execute it.

After that:
```
(cellrank) [giovanni.palla@vicb-submit-02 cellrank]$ python-vendorize
Collecting git+git://github.com/msmdev/msmtools@f9ff7469ebdc9cd9e7e42dac33eb3d7fc23b35ee
  Cloning git://github.com/msmdev/msmtools (to revision f9ff7469ebdc9cd9e7e42dac33eb3d7fc23b35ee) to /tmp/pip-req-build-_0muz_m0
  Running command git clone -q git://github.com/msmdev/msmtools /tmp/pip-req-build-_0muz_m0
  Running command git checkout -q f9ff7469ebdc9cd9e7e42dac33eb3d7fc23b35ee
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python /home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp12onazy8
       cwd: /tmp/pip-req-build-_0muz_m0
  Complete output (56 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
      from . import multiarray
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
      from . import overrides
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: /tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 249, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 99, in <module>
      cmdclass=get_cmdclass(),
    File "setup.py", line 50, in get_cmdclass
      from numpy.distutils.command.build_ext import build_ext
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
      from . import core
    File "/tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
      raise ImportError(msg)
  ImportError:

  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.

  We have compiled some common reasons and troubleshooting tips at:

      https://numpy.org/devdocs/user/troubleshooting-importerror.html

  Please note and check the following:

    * The Python version is: Python3.7 from "/home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python"
    * The NumPy version is: "1.19.0"

  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.

  Original error was: /tmp/pip-build-env-5vch3lyj/overlay/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python /home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp12onazy8 Check the logs for full command output.
Traceback (most recent call last):
  File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python-vendorize", line 20, in <module>
    main()
  File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python-vendorize", line 10, in main
    vendorize_requirements(path="vendorize.toml")
  File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/vendorize/__init__.py", line 20, in vendorize_requirements
    target_directory=target_directory,
  File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/vendorize/__init__.py", line 28, in vendorize_requirement
    cwd=cwd)
  File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip', 'install', '--no-dependencies', '--target', 'cellrank/_vendor', 'git+git://github.com/msmdev/msmtools@f9ff7469ebdc9cd9e7e42dac33eb3d7fc23b35ee']' returned non-zero exit status 1.
```

**Comment by giovp** [comment]
btw, as per #264, I managed to install everything with conda.

**Comment by giovp** [comment]
by installing everything with conda, and then doing `pip install -e .` in the cloned repo, I had this error afteward:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-76a7a5a493ce> in <module>
     10 from scipy import sparse
     11 
---> 12 import cellrank as cr
     13 import scvelo as scv
     14 

/mnt/home/icb/giovanni.palla/cellrank/cellrank/__init__.py in <module>
      2 from scanpy import settings
      3 
----> 4 import cellrank.tools as tl
      5 import cellrank.utils as ul
      6 import cellrank.logging

/mnt/home/icb/giovanni.palla/cellrank/cellrank/tools/__init__.py in <module>
      3 from cellrank.tools._utils import partition, cyto_trace
      4 from cellrank.tools._lineage import Lineage
----> 5 from cellrank.tools._lineages import lineages
      6 from cellrank.tools.estimators import GPCCA, CFLARE
      7 from cellrank.tools._root_final import root_states, final_states

/mnt/home/icb/giovanni.palla/cellrank/cellrank/tools/_lineages.py in <module>
      9 from cellrank.tools.kernels import VelocityKernel
     10 from cellrank.tools._constants import LinKey, StateKey, Direction, _transition
---> 11 from cellrank.tools.estimators import GPCCA, CFLARE
     12 from cellrank.tools.estimators._base_estimator import BaseEstimator
     13 

/mnt/home/icb/giovanni.palla/cellrank/cellrank/tools/estimators/__init__.py in <module>
      1 # -*- coding: utf-8 -*-
----> 2 from cellrank.tools.estimators._gppca import GPCCA
      3 from cellrank.tools.estimators._cflare import CFLARE

/mnt/home/icb/giovanni.palla/cellrank/cellrank/tools/estimators/_gppca.py in <module>
     32 from cellrank.tools.kernels._kernel import KernelExpression
     33 from cellrank.tools.estimators._base_estimator import BaseEstimator
---> 34 from cellrank._vendor.msmtools.analysis.dense.gpcca import GPCCA as _GPCCA
     35 
     36 AnnData = TypeVar("AnnData")

ModuleNotFoundError: No module named 'cellrank._vendor.msmtools'
```

I then went to msmtools page and installed it via conda.
I then had to reinstall cellrank with `pip install cellrank` (without krylov)

**Comment by giovp** [comment]
After that, no new errors aaaand:
![image](https://user-images.githubusercontent.com/25887487/87440540-66762e00-c5f2-11ea-91bc-fdf750972dd6.png)

guys, 200k data points in ~2 minutes... 🚀  🚀  🚀 
Really impressive! 

Thank you a lot for the support!

**Comment by giovp** [comment]
ah, one last thing:
```python
import msmtools

msmtools.__version__

> 1.2.5
```

**Comment by Marius1311** [comment]
Pretty amazing, thanks for sharing this!!!

**Comment by Marius1311** [comment]
The next thing to try for this huge matrix would be the computation of absorption probabilities, that may take just a bit longer. However, we have parallelised and use PETSc for that as well now, so should work as well.

**Comment by giovp** [comment]
happy to test it, let me know if/when

**Comment by Marius1311** [comment]
Implementation is ready, simply run `g.compute_absorption_probabilities` once you have computed the metastable states.
