### ISSUE TITLE
Installing msmstools dev gives error

### ISSUE THREAD

**Issue by giovp** [theislab/cellrank#221]
Hi,

as per msmdev/msmtools#14

I tried to checkout on that PR and install msmtools with `pip intall -e .`. Got an error and so wasn't able to install it:
```
(cellrank) [giovanni.palla@vicb-submit-02 msmtools]$ pip install -e .
Obtaining file:///storage/groups/ml01/workspace/giovanni.palla/msmtools
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python /home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbs1vq37y
       cwd: /storage/groups/ml01/workspace/giovanni.palla/msmtools
  Complete output (56 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
      from . import multiarray
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
      from . import overrides
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
      from numpy.core._multiarray_umath import (
  ImportError: /tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 91, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 127, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 249, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 99, in <module>
      cmdclass=get_cmdclass(),
    File "setup.py", line 50, in get_cmdclass
      from numpy.distutils.command.build_ext import build_ext
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
      from . import core
    File "/tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
      raise ImportError(msg)
  ImportError:

  IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

  Importing the numpy C-extensions failed. This error can happen for
  many reasons, often due to issues with your setup or how NumPy was
  installed.

  We have compiled some common reasons and troubleshooting tips at:

      https://numpy.org/devdocs/user/troubleshooting-importerror.html

  Please note and check the following:

    * The Python version is: Python3.7 from "/home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python"
    * The NumPy version is: "1.19.0"

  and make sure that they are the versions you expect.
  Please carefully study the documentation linked above for further help.

  Original error was: /tmp/pip-build-env-opew6_c_/overlay/lib/python3.7/site-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so: failed to map segment from shared object: Operation not permitted

  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/icb/giovanni.palla/miniconda3/envs/cellrank/bin/python /home/icb/giovanni.palla/miniconda3/envs/cellrank/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpbs1vq37y Check the logs for full command output.
```

would be cool to be able to install that PR so to assess if memory issues are gone for my dataset. Thank you!

btw really impressive tool guys, congrats!

**Comment by Marius1311** [comment]
Thanks @giovp , we will look into this!

**Comment by Marius1311** [comment]
The easiest is probably to wait until https://github.com/msmdev/msmtools/pull/14 is on master, then you can just re-install cellrank and you have these changes included.

**Comment by michalk8** [comment]
Maybe this is helpful - it may be a permission issue https://github.com/numpy/numpy/issues/15102 Is `/tmp` on a separate partition?

**Comment by Marius1311** [comment]
Hopefully, this should be fixed now that the PR is merged @giovp

**Comment by Marius1311** [comment]
@giovp , is this solved?

**Comment by giovp** [comment]
see #210 solved, thank you!
