### ISSUE TITLE
Installing from pip with option krylov

### ISSUE THREAD

**Issue by mbuttner** [theislab/cellrank#264]
I'm running `pip install cellrank[krylov]` and I get
```
Collecting petsc>=3.13.0; extra == "krylov"
  Using cached petsc-3.13.3.tar.gz (14.9 MB)
Collecting mpi4py>=3.0.3; extra == "krylov"
  Using cached mpi4py-3.0.3.tar.gz (1.4 MB)
Collecting slepc>=3.13.0; extra == "krylov"
  Using cached slepc-3.13.2.tar.gz (4.8 MB)
Collecting slepc4py>=3.13.0; extra == "krylov"
  Using cached slepc4py-3.13.0.tar.gz (815 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/maren.buettner/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/setup.py'"'"'; __file__='"'"'/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa
         cwd: /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/
    Complete output (54 lines):
    running egg_info
    creating /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info
    writing /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info/PKG-INFO
    writing dependency_links to /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info/dependency_links.txt
    writing requirements to /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info/requires.txt
    writing top-level names to /private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info/top_level.txt
    writing manifest file '/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-pip-egg-info-2c58k_sa/slepc4py.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/setup.py", line 260, in <module>
        main()
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/setup.py", line 257, in main
        run_setup()
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/setup.py", line 138, in run_setup
        **setup_args)
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/command/sdist.py", line 226, in add_defaults
        self._add_defaults_python()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/site-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/command/build_py.py", line 45, in finalize_options
        ('force', 'force'))
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/cmd.py", line 287, in set_undefined_options
        src_cmd_obj.ensure_finalized()
      File "/Users/maren.buettner/anaconda3/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/conf/slepcconf.py", line 137, in finalize_options
        _build.finalize_options(self)
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/conf/baseconf.py", line 398, in finalize_options
        self.petsc_dir  = config.get_petsc_dir(self.petsc_dir)
      File "/private/var/folders/v1/qzhs5x9168z7bzbctc1j3539c6zy34/T/pip-install-f2ykb5i2/slepc4py/conf/baseconf.py", line 336, in get_petsc_dir
        petsc_dir = petsc.get_petsc_dir()
    AttributeError: module 'petsc' has no attribute 'get_petsc_dir'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

```pytb
...
```

#### Versions:
cellrank==1.0.0-b.8 scanpy==1.5.1 anndata==0.7.3 numpy==1.17.4 scipy==1.4.1 pandas==0.25.2 scikit-learn==0.21.3 statsmodels==0.10.1 python-igraph==0.7.1 scvelo==0.2.1
> ...

**Comment by michalk8** [comment]
This is a know issue when installing PETSc - sometimes it does work, sometimes it doesn't, see: https://bitbucket.org/petsc/petsc4py/issues/132/attributeerror-module-petsc-has-no
In short, `petsc` must be installed prior to `petsc4py` I'm trying to find a workaround, but so far, no luck.
I'd recommend installing it as described in the dependencies section.
Lastly, there was a huge bugfix in https://github.com/theislab/cellrank/pull/263, so I'd recommend either getting a development version or waiting a few minutes until the new release is on PyPI.

**Comment by giovp** [comment]
got same error, will try to install from cloned repo

**Comment by giovp** [comment]
Installing by clonin the repo did not work.

Installing everything with conda worked. Also, the nice thing is that I just had to specificy `conda install -c anaconda mpi4py petsc4py slepcpy` cause the other 3 packages were automatically installed as dependencies.
After that, I also managed to install dev version via cloned directory.

Random tip, but you could also consider [mamba](https://github.com/TheSnakePit/mamba) as faster alternative from conda

**Comment by mbuttner** [comment]
Thank you @giovp for the tip. I tried `conda install -c anaconda mpi4py petsc4py slepcpy`, but it gave the following error.
```
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - petsc4py
  - slepcpy

Current channels:

  - https://conda.anaconda.org/anaconda/osx-64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by giovp** [comment]
try `conda install -c conda-forge mpi4py petsc4py slepcpy`

**Comment by mbuttner** [comment]
Thanks for the comment. I used a different solution: I created a new conda environment and executed `conda install -c conda-forge -c bioconda cellrank-krylov`, which worked charmingly well.

**Comment by giovp** [comment]
the paths to conda install are infinite
![Alt Text](https://media.giphy.com/media/I7V6Te1Ka0U00/giphy.gif)

**Comment by Marius1311** [comment]
@michalk8 , I would close this if you agree.

**Comment by michalk8** [comment]
Agreed.
