### ISSUE TITLE
Improve the heatmap plotting function

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#280]
- [x] Additional function parameters, change functionality or change defaults?
- [ ] New estimator in `cr.tl.estimators`?
- [ ] New kernel in `cr.tl.kernels`?
- [ ] New gene trend model in `cr.ul.models`?
- [ ] New plotting function in `cr.pl`?
- [ ] Other?

Gene ordering works now, and it's great. I just have some minor comments. I'm posting a heatmap I'm getting below:
![image](https://user-images.githubusercontent.com/24494650/88264621-5b935b80-cccc-11ea-8270-1c520966431f.png)

Comments
- the space between the title `Beta` and the actual heatmap is much too large
- the two bars at the top, for clusters and abs. probs, are too large, i.e. I would reduce their height, look at scvelo's heatmap function, it looks much better there

**Comment by michalk8** [comment]
The title is a bit tricky to set, because I try to estimate it's position (based on the top bars).
As for the bars, they are defines as the proportion of the heatmap, so it should be an easy fix.

**Comment by Marius1311** [comment]
Okay, don't worry much about the title then and let's just fix the bars.

**Comment by michalk8** [comment]
Ok, will do. I have a small request - my kernel dies because of C stack error, see below, when running the following:
```python
import cellrank as cr
adata = cr.read(<path to processed pancreas data>)
model = cr.ul.models.GamMGCVModel(adata)
cr.pl.heatmap(adata, model, genes=adata.var_names[:30], time_key='dpt_pseudotime',
              lineages='Epsilon',
              n_jobs=4)
```
@Marius1311 could you please try running it to see if it's also the issue? I've been trying to figure out https://github.com/theislab/cellrank/issues/279 and `cr.pl.heatmap` doesn't use PETSc/SLEPc - but there were threads (one on Firedrake) that mentions the that the message is irrelevant to the cause.

Here's the error I got now regarding the C-stack:
```
Error: C stack usage  139189340036 is too close to the limit
Error: C stack usage  139189340084 is too close to the limit
Error: C stack usage  139189340084 is too close to the limit
Error: C stack usage  139189339572 is too close to the limit
Fatal error: unable to initialize the JIT

[I 11:11:42.179 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 74f398bd-d702-4260-8a7d-f2c2710a0643 restarted
Traceback (most recent call last):
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 567, in initialize
    self.init_sockets()
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 271, in init_sockets
    self.shell_port = self._bind_socket(self.shell_socket, self.shell_port)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 218, in _bind_socket
    return self._try_bind_socket(s, port)
  File "/home/michal/.miniconda3/envs/cellrank/lib/python3.8/site-packages/ipykernel/kernelapp.py", line 194, in _try_bind_socket
    s.bind("tcp://%s:%i" % (self.ip, port))
  File "zmq/backend/cython/socket.pyx", line 550, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 26, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in us
```

**Comment by Marius1311** [comment]
Hi Mike, I'm just running the code snippet you posted above. The first observation is that, as in #279, when I start jupyter lab from my base conda environment, the kernel dies with the error message from #279. I'm repeating the same thing now, but starting my jupyter lab from a different conda environment where rpy2 is installed.

**Comment by Marius1311** [comment]
In this second scenario, I get the correct plot and the kernel does not die. However, when I check my terminal for the jupyter log, I find 

```python
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
------------------------------------------------------------------------
[0]PETSC ERROR: [0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
------------------------------------------------------------------------
Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
------------------------------------------------------------------------
[0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: [0]PETSC ERROR: Caught signal number 15 Terminate: Some process (or the batch system) has told this process to end
[0]PETSC ERROR: or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: [0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
likely location of problem given in stack below
likely location of problem given in stack below
[0]PETSC ERROR: [0]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: likely location of problem given in stack below
[0]PETSC ERROR: [0]PETSC ERROR: [0]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
Note: The EXACT line numbers in the stack are not available,
---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: [0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR:       INSTEAD the line number of the start of the function
      INSTEAD the line number of the start of the function
[0]PETSC ERROR: [0]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
      is given.
      is given.
[0]PETSC ERROR:       INSTEAD the line number of the start of the function
[0]PETSC ERROR: [0]PETSC ERROR:       is given.
or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: likely location of problem given in stack below
[0]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
[0]PETSC ERROR:       INSTEAD the line number of the start of the function
[0]PETSC ERROR:       is given.
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
system msg for write_line failure : Bad file descriptor
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
system msg for write_line failure : Bad file descriptor
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
system msg for write_line failure : Bad file descriptor
application called MPI_Abort(MPI_COMM_WORLD, 50152059) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=50152059
:
system msg for write_line failure : Bad file descriptor
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 13 Broken Pipe: Likely while reading or writing to a socket
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://www.mcs.anl.gov/petsc/documentation/faq.html#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple Mac OS X to find memory corruption errors
[0]PETSC ERROR: likely location of problem given in stack below
[0]PETSC ERROR: ---------------------  Stack Frames ------------------------------------
[0]PETSC ERROR: Note: The EXACT line numbers in the stack are not available,
[0]PETSC ERROR:       INSTEAD the line number of the start of the function
[0]PETSC ERROR:       is given.
```
