### ISSUE TITLE
Can't commit any longer

### ISSUE THREAD

**Issue by Marius1311** [theislab/cellrank#362]
Just pulled from master, opened a new branch and tried to commit something. Got
```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
Check the log at /Users/marius/.cache/pre-commit/pre-commit.log
```

When I actually check which version I have, I get 
```
pre-commit                2.7.1                    pypi_0    pypi
```

So this does not make sense?

When I check the log in `/Users/marius/.cache/pre-commit/pre-commit.log`, I find

```
pre-commit version: 2.5.1
sys.version:
    3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 13:42:17) 
    [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
sys.executable: /Users/marius/miniconda3/envs/cellrank/bin/python
os.name: posix
sys.platform: darwin

### error information

An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
```

```
Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 371, in check
    fn(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/clientlib.py", line 36, in check_min_version
    f'pre-commit version {version} is required but version '
cfgv.ValidationError: 
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 371, in check
    fn(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/clientlib.py", line 36, in check_min_version
    f'pre-commit version {version} is required but version '
cfgv.ValidationError: 
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 371, in check
    fn(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/clientlib.py", line 36, in check_min_version
    f'pre-commit version {version} is required but version '
cfgv.ValidationError: 
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 371, in check
    fn(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/clientlib.py", line 36, in check_min_version
    f'pre-commit version {version} is required but version '
cfgv.ValidationError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/error_handler.py", line 56, in error_handler
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/main.py", line 372, in main
    args=args.rest[1:],
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/commands/hook_impl.py", line 217, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/commands/run.py", line 366, in run
    config = load_config(config_file)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 43, in reraise_as
    raise tp(e).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 40, in reraise_as
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 408, in load_from_filename
    return apply_defaults(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 407, in load_from_filename
    validate(data, schema)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 376, in validate
    schema.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 244, in check
    item.check(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 34, in validate_context
    raise ValidationError(e, ctx=msg).with_traceback(tb)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 31, in validate_context
    yield
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 54, in _check_optional
    self.check_fn(dct[self.key])
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/cfgv.py", line 371, in check
    fn(v)
  File "/Users/marius/miniconda3/envs/cellrank/lib/python3.6/site-packages/pre_commit/clientlib.py", line 36, in check_min_version
    f'pre-commit version {version} is required but version '
pre_commit.clientlib.InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.

```

Running  `pip install --upgrade pre-commit` does not change anything about this. 
```

**Comment by michalk8** [comment]
Try `pre-commit autoupdate`

**Comment by Marius1311** [comment]
Just tried that, the bug persists nontheless.

**Comment by Marius1311** [comment]
I get 

```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.7.1 is required but version 2.5.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
Check the log at /Users/marius/.cache/pre-commit/pre-commit.log
```

**Comment by michalk8** [comment]
Strange. You could either create a new conda environment, since this one seems to be corrupted, or change the version to `2.5.1` here https://github.com/theislab/cellrank/blob/master/.pre-commit-config.yaml#L9.

**Comment by Marius1311** [comment]
I just created an entirely new conda environment and the same error persists.

**Comment by Marius1311** [comment]
works again after changing the requirements!

**Comment by Marius1311** [comment]
I have the same problem again, can't commit. The error is
```
An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
==> At Config()
==> At key: minimum_pre_commit_version
=====> pre-commit version 2.9.0 is required but version 2.7.1 is installed.  Perhaps run `pip install --upgrade pre-commit`.
Check the log at /Users/marius/.cache/pre-commit/pre-commit.log
```

Again, conda tells me I have 
```
pre-commit                2.9.0                    pypi_0    pypi
```

**Comment by Marius1311** [comment]
I already tried upgrading using pip with `--no-cache-dir --force-reinstall`

**Comment by Marius1311** [comment]
I also can't lower the requirements for pre-commit because one of the hooks depends on 2.9.0

**Comment by Marius1311** [comment]
I also tried uninstalling and re-installing pre-commit from conda-forge, no success either.

**Comment by michalk8** [comment]
What do you get when you run `which pre-commit` and `pre-commit --version`?
If it doesn't produce the correct path/version, let's discuss on Zoom. You can disable the checks by running `git commit --no-verify` in the meantime.

**Comment by Marius1311** [comment]
`which pre-commit` yields `/Users/marius/miniconda3/envs/cellrank_revision/bin/pre-commit`, i.e. it uses the one from my conda environment. `pre-commit --version` yields `pre-commit 2.9.3`

**Comment by Marius1311** [comment]
Don't worry about this now, we can solve it in our meeting after your exam on friday.

**Comment by Marius1311** [comment]
To the following to solve it: 
1. Remove the cache: `pre-commit clean`
1. uninstall pre-commit
1. re-install pre-commit: ` pip install pre-commit --force-reinstall --no-cache-dir`
1. install pre-commit: `pre-commit install` 

This fixed it on my machine.
