### ISSUE TITLE
Problems with moment function

### ISSUE THREAD

**Issue by tbrunetti** [theislab/cellrank#574]
...
Hello,

I am trying to work through your CellRank tutorial beyond the RNA velocity using the zebrafish data set (https://cellrank.readthedocs.io/en/stable/beyond_rna_velocity.html#Pre-process-the-data).  Everything works fine, until the `moments` function is encountered, and it throws a really long error after running this command:
```
scv.pp.moments(adata, n_pcs=30, n_neighbors=30)
```

I am using a Python version 3.9.2 on my Linux OS.  I am assuming it is a problem in the Numba package, however, I cannot figure out how to resolve the issue from my end:

```
computing neighbors

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-10-057178b4a97c> in <module>
----> 1 scv.pp.moments(adata, n_pcs=30, n_neighbors=30)

~/.local/lib/python3.9/site-packages/scvelo/preprocessing/moments.py in moments(data, n_neighbors, n_pcs, mode, method, use_rep, use_highly_variable, copy)
     62 
     63     if n_neighbors is not None and n_neighbors > get_n_neighs(adata):
---> 64         neighbors(
     65             adata,
     66             n_neighbors=n_neighbors,

~/.local/lib/python3.9/site-packages/scvelo/preprocessing/neighbors.py in neighbors(adata, n_neighbors, n_pcs, use_rep, use_highly_variable, knn, random_state, method, metric, metric_kwds, num_threads, copy)
    161             warnings.simplefilter("ignore")
    162             neighbors = Neighbors(adata)
--> 163             neighbors.compute_neighbors(
    164                 n_neighbors=n_neighbors,
    165                 knn=knn,

~/.local/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    748             # we need self._distances also for method == 'gauss' if we didn't
    749             # use dense distances
--> 750             self._distances, self._connectivities = _compute_connectivities_umap(
    751                 knn_indices,
    752                 knn_distances,

~/.local/lib/python3.9/site-packages/scanpy/neighbors/__init__.py in _compute_connectivities_umap(knn_indices, knn_dists, n_obs, n_neighbors, set_op_mix_ratio, local_connectivity)
    353         # umap 0.5.0
    354         warnings.filterwarnings("ignore", message=r"Tensorflow not installed")
--> 355         from umap.umap_ import fuzzy_simplicial_set
    356 
    357     X = coo_matrix(([], ([], [])), shape=(n_obs, 1))

~/.local/lib/python3.9/site-packages/umap/__init__.py in <module>
----> 1 from .umap_ import UMAP
      2 
      3 # Workaround: https://github.com/numba/numba/issues/3341
      4 import numba
      5 

~/.local/lib/python3.9/site-packages/umap/umap_.py in <module>
     60 try:
     61     # Use pynndescent, if installed (python 3 only)
---> 62     from pynndescent import NNDescent
     63     from pynndescent.distances import named_distances as pynn_named_distances
     64     from pynndescent.sparse import sparse_named_distances as pynn_sparse_named_distances

~/.local/lib/python3.9/site-packages/pynndescent/__init__.py in <module>
      1 import pkg_resources
      2 import numba
----> 3 from .pynndescent_ import NNDescent, PyNNDescentTransformer
      4 
      5 # Workaround: https://github.com/numba/numba/issues/3341

~/.local/lib/python3.9/site-packages/pynndescent/pynndescent_.py in <module>
     19 import heapq
     20 
---> 21 import pynndescent.sparse as sparse
     22 import pynndescent.sparse_nndescent as sparse_nnd
     23 import pynndescent.distances as pynnd_dist

~/.local/lib/python3.9/site-packages/pynndescent/sparse.py in <module>
    341     },
    342 )
--> 343 def sparse_alternative_jaccard(ind1, data1, ind2, data2):
    344     num_non_zero = arr_union(ind1, ind2).shape[0]
    345     num_equal = arr_intersect(ind1, ind2).shape[0]

~/.local/lib/python3.9/site-packages/numba/core/decorators.py in wrapper(func)
    216             with typeinfer.register_dispatcher(disp):
    217                 for sig in sigs:
--> 218                     disp.compile(sig)
    219                 disp.disable_compile()
    220         return disp

~/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, sig)
    817             self._cache_misses[sig] += 1
    818             try:
--> 819                 cres = self._compiler.compile(args, return_type)
    820             except errors.ForceLiteralArg as e:
    821                 def folded(args, kws):

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in compile(self, args, return_type)
     80             return retval
     81         else:
---> 82             raise retval
     83 
     84     def _compile_cached(self, args, return_type):

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     90 
     91         try:
---> 92             retval = self._compile_core(args, return_type)
     93         except errors.TypingError as e:
     94             self._failed_cache[key] = e

~/.local/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    103 
    104         impl = self._get_implementation(args, {})
--> 105         cres = compiler.compile_extra(self.targetdescr.typing_context,
    106                                       self.targetdescr.target_context,
    107                                       impl,

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    625     pipeline = pipeline_class(typingctx, targetctx, library,
    626                               args, return_type, flags, locals)
--> 627     return pipeline.compile_extra(func)
    628 
    629 

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in compile_extra(self, func)
    361         self.state.lifted = ()
    362         self.state.lifted_from = None
--> 363         return self._compile_bytecode()
    364 
    365     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_bytecode(self)
    423         """
    424         assert self.state.func_ir is None
--> 425         return self._compile_core()
    426 
    427     def _compile_ir(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    403                 self.state.status.fail_reason = e
    404                 if is_final_pipeline:
--> 405                     raise e
    406         else:
    407             raise CompilerError("All available pipelines exhausted")

~/.local/lib/python3.9/site-packages/numba/core/compiler.py in _compile_core(self)
    394             res = None
    395             try:
--> 396                 pm.run(self.state)
    397                 if self.state.cr is not None:
    398                     break

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    339                     (self.pipeline_name, pass_desc)
    340                 patched_exception = self._patch_error(msg, e)
--> 341                 raise patched_exception
    342 
    343     def dependency_analysis(self):

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in run(self, state)
    330                 pass_inst = _pass_registry.get(pss).pass_inst
    331                 if isinstance(pass_inst, CompilerPass):
--> 332                     self._runPass(idx, pass_inst, state)
    333                 else:
    334                     raise BaseException("Legacy pass in use")

~/.local/lib/python3.9/site-packages/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    289             mutated |= check(pss.run_initialization, internal_state)
    290         with SimpleTimer() as pass_time:
--> 291             mutated |= check(pss.run_pass, internal_state)
    292         with SimpleTimer() as finalize_time:
    293             mutated |= check(pss.run_finalizer, internal_state)

~/.local/lib/python3.9/site-packages/numba/core/compiler_machinery.py in check(func, compiler_state)
    262 
    263         def check(func, compiler_state):
--> 264             mangled = func(compiler_state)
    265             if mangled not in (True, False):
    266                 msg = ("CompilerPass implementations should return True/False. "

~/.local/lib/python3.9/site-packages/numba/core/typed_passes.py in run_pass(self, state)
     90                               % (state.func_id.func_name,)):
     91             # Type inference
---> 92             typemap, return_type, calltypes = type_inference_stage(
     93                 state.typingctx,
     94                 state.func_ir,

~/.local/lib/python3.9/site-packages/numba/core/typed_passes.py in type_inference_stage(typingctx, interp, args, return_type, locals, raise_errors)
     68 
     69         infer.build_constraint()
---> 70         infer.propagate(raise_errors=raise_errors)
     71         typemap, restype, calltypes = infer.unify(raise_errors=raise_errors)
     72 

~/.local/lib/python3.9/site-packages/numba/core/typeinfer.py in propagate(self, raise_errors)
   1069                                   if isinstance(e, ForceLiteralArg)]
   1070                 if not force_lit_args:
-> 1071                     raise errors[0]
   1072                 else:
   1073                     raise reduce(operator.or_, force_lit_args)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x7f22cb1cb4c0>) found for signature:
 
 >>> run_quicksort(array(int32, 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 150.
    With argument(s): '(array(int32, 1d, C))':
   Rejected as the implementation raised a specific error:
     UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
   Use of unsupported opcode (LOAD_ASSERTION_ERROR) found
   
   File "../../.local/lib/python3.9/site-packages/numba/misc/quicksort.py", line 180:
       def run_quicksort(A):
           <source elided>
               while high - low >= SMALL_QUICKSORT:
                   assert n < MAX_STACK
                   ^

  raised from /home/tonya/.local/lib/python3.9/site-packages/numba/core/byteflow.py:269

During: resolving callee type: Function(<function make_quicksort_impl.<locals>.run_quicksort at 0x7f22cb1cb4c0>)
During: typing of call at /home/tonya/.local/lib/python3.9/site-packages/numba/np/arrayobj.py (5007)


File "../../.local/lib/python3.9/site-packages/numba/np/arrayobj.py", line 5007:
    def array_sort_impl(arr):
        <source elided>
        # Note we clobber the return value
        sort_func(arr)
        ^

During: lowering "$14call_method.5 = call $12load_method.4(func=$12load_method.4, args=[], kws=(), vararg=None)" at /home/tonya/.local/lib/python3.9/site-packages/numba/np/arrayobj.py (5017)
During: lowering "$8call_method.3 = call $4load_method.1(arr, func=$4load_method.1, args=[Var(arr, sparse.py:28)], kws=(), vararg=None)" at /home/tonya/.local/lib/python3.9/site-packages/pynndescent/sparse.py (28)
During: resolving callee type: type(CPUDispatcher(<function arr_unique at 0x7f22cb72dd30>))
During: typing of call at /home/tonya/.local/lib/python3.9/site-packages/pynndescent/sparse.py (41)

During: resolving callee type: type(CPUDispatcher(<function arr_unique at 0x7f22cb72dd30>))
During: typing of call at /home/tonya/.local/lib/python3.9/site-packages/pynndescent/sparse.py (41)


File "../../.local/lib/python3.9/site-packages/pynndescent/sparse.py", line 41:
def arr_union(ar1, ar2):
    <source elided>
    else:
        return arr_unique(np.concatenate((ar1, ar2)))
        ^

During: resolving callee type: type(CPUDispatcher(<function arr_union at 0x7f22cb72de50>))
During: typing of call at /home/tonya/.local/lib/python3.9/site-packages/pynndescent/sparse.py (344)

During: resolving callee type: type(CPUDispatcher(<function arr_union at 0x7f22cb72de50>))
During: typing of call at /home/tonya/.local/lib/python3.9/site-packages/pynndescent/sparse.py (344)


File "../../.local/lib/python3.9/site-packages/pynndescent/sparse.py", line 344:
def sparse_alternative_jaccard(ind1, data1, ind2, data2):
    num_non_zero = arr_union(ind1, ind2).shape[0]
    ^
```

**Comment by michalk8** [comment]
Hi @tbrunetti ,

what's your numba version? I usually still have problems with `umap  and`numba>=0.53.0`, with `numba==0.52.0`, it works fine.

**Comment by tbrunetti** [comment]
@michalk8 

Thank you!  I actually ended up using the conda environment instead and it works.  Thanks!
